### ISSUE TITLE
N-12. MOD_NN_N - __mod__

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#10]
Остаток от деления большего натурального числа на меньшее или равное натуральное с остатком(делитель отличен от нуля)

Подмодули:
- DIV_NN_N
- SUB_NDN_N

**Comment by No1ball** [comment]
Работает неверно.
![2021-04-05_13-30-00](https://user-images.githubusercontent.com/81362127/113565102-20934700-9613-11eb-82f6-b04683c097a9.png)
![image](https://user-images.githubusercontent.com/81362127/113565116-2721be80-9613-11eb-8cce-300737da5baa.png)

**Comment by No1ball** [comment]
Работает верно.
