### ISSUE TITLE
N-9. SUB_NDN_N - sub_dn

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#12]
Вычитание из натурального другого натурального, умноженного на цифру для случая с неотрицательным результатом

Подмодули:
- SUB_NN_N
- MUL_ND_N
- COM_NN_D

**Comment by No1ball** [comment]
Работает неверно для длинных чисел.

**Comment by No1ball** [comment]
Работает верно.

**Comment by No1ball** [comment]
Работает верно.
