### ISSUE TITLE
N-3. ADD_1N_N - increment

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#3]
Добавление 1 к натуральному числу

**Comment by No1ball** [comment]
Работает неверно.

**Comment by Dusty305** [comment]
Модуль был обновлен. Требует проверки

**Comment by No1ball** [comment]
Работает неверно для 99, и чисел состоящих из одних 9.

**Comment by Dusty305** [comment]
Баг исправлен, модуль работает для чисел вида 99...9

**Comment by No1ball** [comment]
Работает верно.
