### ISSUE TITLE
Z-10. MOD_ZZ_Z - __mod__

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#30]
Остаток от деления целого на целое(делитель отличен от нуля)

Подмодули:
- DIV_ZZ_Z
- MUL_ZZ_Z
- SUB_ZZ_Z
- MUL_ZM_Z

**Comment by No1ball** [comment]
Работает неправильно на отрицательных числах.

**Comment by No1ball** [comment]
Работает верно.
