### ISSUE TITLE
Q-5. ADD_QQ_Q - __add__

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#33]
Сложение дробей

Подмодули:
- LCM_NN_N
- MUL_ZZ_Z
- ADD_ZZ_Z

**Comment by No1ball** [comment]
Работает неверно. Попытка работать с объектами класса Natural, как с объектами класса int. В каждой операции надо приводить все к классу Natural.

**Comment by No1ball** [comment]
Работает верно.
