### ISSUE TITLE
Q-6. SUB_QQ_Q - __sub__

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#34]
Вычитание дробей

Подмодули:
- LCM_NN_N
- MUL_ZZ_Z
- SUB_ZZ_Z

**Comment by No1ball** [comment]
Работает неверно. Результатом 11/3 - 1/3 выдает 9/3.

**Comment by Dusty305** [comment]
Ошибка в методе div_dk, а не в данном модуле. Баг исправлен, требуется повторная проверка

**Comment by No1ball** [comment]
Работает верно.
