### ISSUE TITLE
P-1. ADD_PP_P - __add__

### ISSUE THREAD

**Issue by Dusty305** [Dusty305/algebra-clqm#37]
Сложение многочленов

Подмодули:
- ADD_QQ_Q

**Comment by No1ball** [comment]
Работает верно.

**Comment by Dusty305** [comment]
Сложение не работает. Скорее всего либо из-за нового порядка коэффиициентов, либо из-за конструктора, либо из-за exception

**Comment by Dusty305** [comment]
![image](https://user-images.githubusercontent.com/44769076/116309791-de909780-a7b1-11eb-850e-3bad04d5cbe0.png)
![image](https://user-images.githubusercontent.com/44769076/116309806-e3554b80-a7b1-11eb-9046-8209b557b205.png)

**Comment by Dusty305** [comment]
Проблема была в конструкторе
